name: Android CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Checkout 
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: .
        
      - name: Build with Gradle
        run: ./gradlew assembleDebug
        working-directory: .
        
      # - name: Run ktlintCheck
      #   run: ./gradlew ktlintCheck
      #   working-directory: .
        
